export const BASE_URL = 'http://109.201.96.70:8081/api'

export const beerList = [
   {
     "id": 115,
     "name": "BestBeer",
     "description": "very strong beer",
     "averageRating": 3.4,
     "style": "al",
     "image": "http://109.201.96.70:8081/api/beer/images/04_10_2023_07_17_52_news4.png",
     "abv": 11,
     "ibu": 3,
     "breweryId": 4,
     "totalReviews": 3,
     "breweryName": "Selfmade Brewery",
     "link": "http://localhost:5173/Selfmade_Brewery/BestBeer_115"
   },
   {
     "id": 111,
     "name": "B is for blueberry",
     "description": "B is for Blueberry — гозе с черникой. В первом глотке ощущается лимонная кислинка и дрожжевая пряность, после добавляются оттенки черники и сливы.",
     "averageRating": 2.22,
     "style": "кислуй эль",
     "image": "http://109.201.96.70:8081/api/beer/images/04_10_2023_05_38_00_scale_1200.jpg",
     "abv": 5.2,
     "ibu": 5,
     "breweryId": 92,
     "totalReviews": 5,
     "breweryName": "Hoppy Machine",
     "link": "http://localhost:5173/Hoppy_Machine/B_is_for_blueberry_111"
   },
   {
     "id": 124,
     "name": "Пиво пенное",
     "description": "Пиво пенное сварено сегодня, разлито завтра, продано после дождичка в четверг, выпито в недалеком будущем ",
     "averageRating": 3.5,
     "style": "пиво",
     "image": "http://109.201.96.70:8081/api/beer/images/19_10_2023_10_56_04_news2.png",
     "abv": 3.4,
     "ibu": 11,
     "breweryId": 123,
     "totalReviews": 2,
     "breweryName": "Я люблю пиво",
     "link": "http://localhost:5173/Я_люблю_пиво/Пиво_пенное_124"
   },
   {
     "id": 137,
     "name": "Super",
     "description": "супер пиво",
     "averageRating": 5.5,
     "style": "пиво",
     "image": null,
     "abv": 4.5,
     "ibu": 3,
     "breweryId": 136,
     "totalReviews": 1,
     "breweryName": "Super",
     "link": "http://localhost:5173/Super/Super_137"
   },
   {
     "id": 184,
     "name": "test",
     "description": "«test»",
     "averageRating": 2.93,
     "style": "lager",
     "image": null,
     "abv": 11,
     "ibu": 3,
     "breweryId": 182,
     "totalReviews": 3,
     "breweryName": "test",
     "link": "http://localhost:5173/test/test_184"
   },
   {
     "id": 114,
     "name": "demo",
     "description": "description",
     "averageRating": 6,
     "style": "lager",
     "image": "http://109.201.96.70:8081/api/beer/images/04_10_2023_07_14_01_center-slade.png",
     "abv": 4.5,
     "ibu": 1,
     "breweryId": 4,
     "totalReviews": 1,
     "breweryName": "Selfmade Brewery",
     "link": "http://localhost:5173/Selfmade_Brewery/demo_114"
   },
   {
     "id": 122,
     "name": "мерзкое",
     "description": "",
     "averageRating": 5.9,
     "style": "",
     "image": null,
     "abv": null,
     "ibu": null,
     "breweryId": 8,
     "totalReviews": 1,
     "breweryName": "Четыре Пивовара",
     "link": "http://localhost:5173/Четыре_Пивовара/мерзкое_122"
   },
   {
     "id": 140,
     "name": "дубль в бд",
     "description": "super beer",
     "averageRating": 0,
     "style": "пиво",
     "image": "http://109.201.96.70:8081/api/beer/images/19_12_2023_11_00_35_Screenshot_1.png",
     "abv": 4.5,
     "ibu": 3,
     "breweryId": 136,
     "totalReviews": 0,
     "breweryName": "Super",
     "link": "http://localhost:5173/Super/дубль_в_бд_140"
   },
   {
     "id": 138,
     "name": "Еще один дубль в бд",
     "description": "супер пиво",
     "averageRating": 0,
     "style": "пиво",
     "image": "http://109.201.96.70:8081/api/beer/images/18_12_2023_15_09_03_Screenshot_110.png",
     "abv": 4.5,
     "ibu": 3,
     "breweryId": 136,
     "totalReviews": 0,
     "breweryName": "Super",
     "link": "http://localhost:5173/Super/Еще_один_дубль_в_бд_138"
   },
   {
     "id": 24,
     "name": "Mead Cherry",
     "description": " Медовуха с вишней",
     "averageRating": 3.83,
     "style": "Mead - Melomel",
     "image": "http://109.201.96.70:8081/api/beer/images/12_09_2023_13_27_04_eIsJqUcdF372PJ2sksBAA.png",
     "abv": 6,
     "ibu": null,
     "breweryId": 6,
     "totalReviews": 6,
     "breweryName": "Степь и Ветер",
     "link": "http://localhost:5173/Степь_и_Ветер/Mead_Cherry_24"
   },
   {
     "id": 11,
     "name": "Tropical Slasher",
     "description": "Наш новый сорт Tropical Slasher в стиле имперского тропического, практически пэстри сауэра призван скрасить трудовые будни тех, кто строил планы на летний отпуск в этом году. Ананасы, манго, кокос, тонкие нотки тонки (попробуйте повторить быстро!). Солодовая база закислялась по методу sour kettle. В результате мы получили напиток с ярко выраженным вкусом тропических фруктов и кокоса, который, на наш взгляд, весьма удачно дополняет лето 2020 года!",
     "averageRating": 0,
     "style": "Sour — Smoothie / Pastry",
     "image": "http://109.201.96.70:8081/api/beer/images/08_09_2023_06_42_59_4473e699245a260bd3238ce6dcc5d6da.jpeg",
     "abv": 7,
     "ibu": 20,
     "breweryId": 4,
     "totalReviews": 0,
     "breweryName": "Selfmade Brewery",
     "link": "http://localhost:5173/Selfmade_Brewery/Tropical_Slasher_11"
   },
   {
     "id": 9,
     "name": "Fruitality",
     "description": "Есть много вещей, которые могут собрать вместе вечером близких (и не очень) людей. Но вещей, способных разжечь в них азарт и первобытные эмоции, намного меньше. Борьба, превозмогание и сладкий миг победы – вот за что мы любим игры-файтинги. Fruitality – это мощный апперкот, микс из фруктов и хмеля, которые ураганом ударов атакуют ваши рецепторы. Во вкусе молочность, сочные фрукты и хмелевая горечь средней интенсивности. Техника двойного хмелевого удара из Simcoe и Equanot пробивает любую защиту. Срочно ищите союзников и будьте осторожны с фруктовым добиванием, Finish him!.",
     "averageRating": 2.1,
     "style": "Фруктовое пиво",
     "image": "http://109.201.96.70:8081/api/beer/images/08_09_2023_06_36_24_641794ab39354f2ab5a6cdc56e93eea7.jpeg",
     "abv": 6.6,
     "ibu": 38,
     "breweryId": 4,
     "totalReviews": 5,
     "breweryName": "Selfmade Brewery",
     "link": "http://localhost:5173/Selfmade_Brewery/Fruitality_9"
   },
   {
     "id": 10,
     "name": "BFG",
     "description": "Культовое оружие геймеров Big F...g Gun снова с нами! Однократный выстрел плазменным зарядом наносит опустошающий удар по противнику и позволяет одним нажатием курка решить множество проблем на поле боя. Так и наш бестселлер поможет вам решить целый спектр задач после трудовых будней всего лишь одной пинтой. Крепкий, плотный и сладковатый эль в стиле Double IPA с обильной, но не доминирующей горечью, большим количеством тропических фруктов во вкусе, обязательно понравится всем почитателям крепких сортов пива. Strong, dense slightly sugary ale with rich though not dominant bitterness, plenty of tropical fruits in flavor. For tempted fans of high-gravity flavors.",
     "averageRating": 3.5,
     "style": "Двойной IPA",
     "image": "http://109.201.96.70:8081/api/beer/images/08_09_2023_06_38_11_36999c7f7f316f72298ef8f1d31dbb47.jpeg",
     "abv": 8,
     "ibu": 75,
     "breweryId": 4,
     "totalReviews": 5,
     "breweryName": "Selfmade Brewery",
     "link": "http://localhost:5173/Selfmade_Brewery/BFG_10"
   },
   {
     "id": 365,
     "name": "test beer",
     "description": "test description",
     "averageRating": 0,
     "style": "тестовый",
     "image": "http://109.201.96.70:8081/api/beer/images/21_06_2024_16_43_02_avatar.png",
     "abv": 1.4,
     "ibu": 7,
     "breweryId": 18,
     "totalReviews": 0,
     "breweryName": "RED ROCKET BREWERY",
     "link": "http://localhost:5173/RED_ROCKET_BREWERY/test_beer_365"
   },
   {
     "id": 366,
     "name": "Ячменный колос",
     "description": "вкус молодости",
     "averageRating": 0,
     "style": "пиво",
     "image": "http://109.201.96.70:8081/api/beer/images/21_06_2024_16_48_29_avatar.png",
     "abv": 4.5,
     "ibu": 4,
     "breweryId": 18,
     "totalReviews": 0,
     "breweryName": "RED ROCKET BREWERY",
     "link": "http://localhost:5173/RED_ROCKET_BREWERY/Ячменный_колос_366"
   },
   {
     "id": 367,
     "name": "Справочник Сотрудники",
     "description": "сидр сидровый",
     "averageRating": 0,
     "style": "сидр",
     "image": "http://109.201.96.70:8081/api/beer/images/21_06_2024_18_05_25_avatar.png",
     "abv": 1.4,
     "ibu": 7,
     "breweryId": 8,
     "totalReviews": 0,
     "breweryName": "Четыре Пивовара",
     "link": "http://localhost:5173/Четыре_Пивовара/Справочник_Сотрудники_367"
   },
   {
     "id": 368,
     "name": "test beer",
     "description": "description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description ",
     "averageRating": 0,
     "style": "пиво",
     "image": "http://109.201.96.70:8081/api/beer/images/24_06_2024_10_13_07_avatar.png",
     "abv": 3.14,
     "ibu": 4,
     "breweryId": 6,
     "totalReviews": 0,
     "breweryName": "Степь и Ветер",
     "link": "http://localhost:5173/Степь_и_Ветер/test_beer_368"
   },
   {
     "id": 369,
     "name": "beer test",
     "description": "description",
     "averageRating": 0,
     "style": "beer",
     "image": "http://109.201.96.70:8081/api/beer/images/25_06_2024_12_35_12_avatar.png",
     "abv": 3.14,
     "ibu": 7,
     "breweryId": 19,
     "totalReviews": 0,
     "breweryName": "REBEL APPLE",
     "link": "http://localhost:5173/REBEL_APPLE/beer_test_369"
   }
 ]

 export const placeList = [
   {
     "placeId": 147,
     "name": "Боченок",
     "address": "г Тверь, тер Автокооператив N13, д 11",
     "description": "Бар \"Боченок\" предагает более 30 сортов крафтого пива",
     "type": "Бар",
     "image": null,
     "city": "Тверь",
     "geoLat": 56.858605,
     "geoLon": 35.911756,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 145,
     "name": "Пиво пенное",
     "address": "г Владимир, ул Бабушкина, д 4",
     "description": "Бар \"Пиво пенное\" предлогает более 30 сортов крафтого пива",
     "type": "Бар",
     "image": null,
     "city": "Владимир",
     "geoLat": 56.169636,
     "geoLon": 40.489315,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 21,
     "name": "Why Not?",
     "address": "ул. Островского. д. 47",
     "description": "Новый взгляд на пиво! Аскетичный бар на улице Островского с огромным количеством крафтового пива со всей...",
     "type": "Бар",
     "image": "http://109.201.96.70:8081/api/place/images/09_09_2023_18_26_42_photo_2018-06-07_19-07-19.jpg",
     "city": "Сочи",
     "geoLat": 43.589508,
     "geoLon": 39.723637,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 125,
     "name": "Армянское пиво",
     "address": "Респ Крым, г Армянск, ул Симферопольская, д 4Д",
     "description": "Всегда свежее пиво с раками и раки со сраками",
     "type": "Бар",
     "image": "http://109.201.96.70:8081/api/place/images/19_10_2023_14_07_47_profile-favorites2.png",
     "city": "Армянск",
     "geoLat": 46.1117833,
     "geoLon": 33.6897774,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 139,
     "name": "Super",
     "address": "г Москва, ул Тверская, д 1",
     "description": "супер бар",
     "type": "Бар",
     "image": "http://109.201.96.70:8081/api/place/images/18_12_2023_15_13_41_Screenshot_110.png",
     "city": "Москва",
     "geoLat": 55.756994,
     "geoLon": 37.614006,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 20,
     "name": "13 rules Bar&Shop",
     "address": "ул. Брюсова. д. 4/1",
     "description": "Bar&Shop Крафтового пива. Всегда в наличии пиво на любой вкус и цвет! 20 кранов и 200 бутылок!",
     "type": "Бар",
     "image": "http://109.201.96.70:8081/api/place/images/09_09_2023_08_31_16_m5w79lIQPJE.jpg",
     "city": "Ковров",
     "geoLat": 56.354661,
     "geoLon": 41.310413,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 91,
     "name": "вечер трудного дня",
     "address": "Владимирская обл, г Ковров, ул Чкалова, д 51",
     "description": "",
     "type": "Магазин",
     "image": "http://109.201.96.70:8081/api/place/images/oLd6gAUZXYI.jpg",
     "city": "Ковров",
     "geoLat": 56.349808,
     "geoLon": 41.311356,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 144,
     "name": "Морячка",
     "address": "г Севастополь, ул Адмирала Грейга , д",
     "description": "",
     "type": "Бар",
     "image": null,
     "city": "Севастополь",
     "geoLat": 44.545449,
     "geoLon": 33.534038,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 131,
     "name": "Oleg",
     "address": "г Москва, ул Тверская, д 1",
     "description": "",
     "type": "Бар",
     "image": "http://109.201.96.70:8081/api/place/images/18_12_2023_12_50_35_Screenshot_13.png",
     "city": "Москва",
     "geoLat": 55.756994,
     "geoLon": 37.614006,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 60,
     "name": "Пивная фактория",
     "address": "Респ Крым, г Армянск, ул Вишнёвая, двлд 1",
     "description": "Описание",
     "type": "Бар",
     "image": "http://109.201.96.70:8081/api/place/images/17_09_2023_18_41_19_vasileostrovskay.png",
     "city": "Армянск",
     "geoLat": 46.105885,
     "geoLon": 33.676735,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 146,
     "name": "Пена в край",
     "address": "г. Ростов",
     "description": "",
     "type": "Бар",
     "image": null,
     "city": "",
     "geoLat": null,
     "geoLon": null,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 58,
     "name": "card-image",
     "address": null,
     "description": "cccccccccccc cccccccc ccccccccccc xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
     "type": "Магазин",
     "image": "http://109.201.96.70:8081/api/place/images/17_09_2023_14_13_55_profile-favorites1.png",
     "city": "Нью-йорк",
     "geoLat": 55.756994,
     "geoLon": 37.614006,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 57,
     "name": "shop",
     "address": null,
     "description": "cccccccccc cccccc xxxxxxxxxxxx",
     "type": "Бар",
     "image": "http://109.201.96.70:8081/api/place/images/17_09_2023_14_11_59_profile-favorites3.png",
     "city": "Москва",
     "geoLat": 55.756994,
     "geoLon": 37.614006,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 185,
     "name": "Пилат понтийский",
     "address": "г Москва, ул Тверская, д 1",
     "description": "В нашем магазине «пилат» вы найдете все что вам нужно",
     "type": "Магазин",
     "image": "http://109.201.96.70:8081/api/place/images/17_01_2024_14_59_56_Screenshot_70.png",
     "city": "Москва",
     "geoLat": 55.756994,
     "geoLon": 37.614006,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 59,
     "name": "Пивнуха",
     "address": "Оренбуг, ул. Ленина, ",
     "description": "Классный бар",
     "type": "Бар",
     "image": "http://109.201.96.70:8081/api/place/images/17_09_2023_14_45_26_profile-favorites2.png",
     "city": "Оренбург",
     "geoLat": null,
     "geoLon": null,
     "setAvailabilityOfSpaceForTheUser": false
   },
   {
     "placeId": 362,
     "name": "Супер БАР",
     "address": "Владимирская обл, г Ковров, ул Владимирская",
     "description": "Лучший бар в Коврове",
     "type": "Магазин",
     "image": "http://109.201.96.70:8081/api/place/images/11_06_2024_13_10_34_avatar.png",
     "city": "Ковров",
     "geoLat": 56.339312,
     "geoLon": 41.29073,
     "setAvailabilityOfSpaceForTheUser": false
   }
 ]

 export const breweryList = [
   {
     "id": 182,
     "name": "test",
     "city": "Оренбург",
     "description": "test «test»",
     "type": "Сидродельня",
     "averageRating": 2.93,
     "image": "http://109.201.96.70:8081/api/brewery/images/17_01_2024_14_18_07_Screenshot_30.png"
   },
   {
     "id": 6,
     "name": "Степь и Ветер",
     "city": "Оренбург",
     "description": "2014 год выдался особенно урожайным на нашей семейной пасеке. Тогда зародилась идея  медоварения, но не того сельского напитка, от которого отнимаются ноги, а мёда новой школы: красивого и ароматного медово-фруктового вина, который займет свое достойное место рядом с другими благородными напитками.  \nНаша торговая марка  Степь и ветер зарегистрированна в 2017 году, после  нескольких лет наших успешных экспериментов. Звучное имя возникло из-за месторасположения. Мы находимся на границе Европы и Азии, где дуют сильные степные ветра и можно увидеть как далеко летают пчёлы.",
     "type": "Медоварня",
     "averageRating": 3.83,
     "image": "http://109.201.96.70:8081/api/brewery/images/07_09_2023_17_27_18_uJS56MgUoFc.jpg"
   },
   {
     "id": 18,
     "name": "RED ROCKET BREWERY",
     "city": "Екатеринбург",
     "description": "Екатеринбургская пивоварня Red Rocket Brewery стартовала в 2020 году и соответственно названию сразу стремительно взлетела на вершину российского Untappd. Это проект двух знаковых для уральского крафта фигур — известного домашнего пивовара Никиты Абсурда и экс-пивовара Jaws Ивана Полушкина, сварившего когда-то всем известную Атомную прачечную.",
     "type": "Пивоварня",
     "averageRating": 0,
     "image": "http://109.201.96.70:8081/api/brewery/images/d8cdfd42ecdf33383a1614eadd42d02d.webp"
   },
   {
     "id": 130,
     "name": "BreweryTest",
     "city": "Оренбург",
     "description": "Пивоварня основана в каком-то году, каким-то чуваком. Крафтовые сорта нашей пивоварни, неоднократно представлялись и побеждали в номинациях на престижных международных конкурсах...",
     "type": "Пивоварня",
     "averageRating": 0,
     "image": null
   },
   {
     "id": 148,
     "name": "Люблю Медовуху",
     "city": "Кострома",
     "description": "Медоварня 'Люблю Медовуху' основана до рождества Христова, ее продукцию любил и ценил Понтий и Пилат во времена похода на Галлию",
     "type": "Медоварня",
     "averageRating": 0,
     "image": null
   },
   {
     "id": 181,
     "name": "Test",
     "city": "Москва",
     "description": "function () {\n          const value = (0,_HelperFunctions_replaceQuotes__WEBPACK_IMPORTED_MODULE_3__.replaceQuotes)(description.value);\n          return value;\n        }",
     "type": "Сидродельня",
     "averageRating": 0,
     "image": "http://109.201.96.70:8081/api/brewery/images/17_01_2024_08_08_48_smart.png"
   },
   {
     "id": 183,
     "name": "Test-2",
     "city": "Оренбург",
     "description": "«test»",
     "type": "Пивоварня",
     "averageRating": 0,
     "image": "http://109.201.96.70:8081/api/brewery/images/17_01_2024_14_19_47_Screenshot_8.png"
   },
   {
     "id": 8,
     "name": "Четыре Пивовара",
     "city": "Владимир",
     "description": "Все началось в 2010. Тогда ребята наткнулись на форум домашних пивоваров, почитали немного и твердо решили, что надо варить свое пиво. Мысль о своем пиве будоражила ум. Масла в огонь подливал тот факт, что они попробовали в одном из московских ресторанов нефильтрованное пшеничное пиво, которое разительно отличалось от всего пробованного ранее.\n\nСкоро они узнали, что стилей пива не 3, а какое-то немыслимое количество. Кастрюльки на протяжении времени росли, появлялись разные девайсы, микроскопы, мешалки, холодильники. Все это время пивоварение оставалось как хобби. В 2014 4BREWERS открыли паб во Владимире. Он работает и сейчас, собирает всех биргиков, друзей биргиков, родственников друзей биргиков и прочих неравнодушных к пиву. Кроме того, там пытаются обращать новых людей (не знакомых с миром пива) в свою веру.",
     "type": "Пивоварня",
     "averageRating": 5.9,
     "image": "http://109.201.96.70:8081/api/brewery/images/0hK4MhyS2gE.jpg"
   },
   {
     "id": 19,
     "name": "REBEL APPLE",
     "city": "Москва",
     "description": "Rebel Apple - альтернативная сидрерия из Москвы, созданная  Александром Ионовым в 2018 году. В 2015 году Александр  впервые сделал сидр из дачных яблок Ярославской области.",
     "type": "Сидродельня",
     "averageRating": 0,
     "image": "http://109.201.96.70:8081/api/brewery/images/ciy8655ip8lt94kkgpxbdvm1nqzm3ez6.webp"
   },
   {
     "id": 12,
     "name": "ATMOSPHERE BREWERY",
     "city": "Клин",
     "description": "Пивоварня Atmosphere — активно развивающаяся пивоварня. Ключевой девиз компании: Стабильность, Качество, Доступность  Стабильность - это то к чему стремится каждая пивоварня, и в Atmosphere brewery стараются уделить этому особое внимание. При производстве пива используется только проверенное и качественное сырье. Каждая партия пива проходит проверку в микробиологической лаборатории.",
     "type": "Пивоварня",
     "averageRating": 0,
     "image": "http://109.201.96.70:8081/api/brewery/images/08_09_2023_06_51_58_6f7c7d66f41ca0004e8da5f6161d518f.webp"
   },
   {
     "id": 16,
     "name": "AF BREW",
     "city": "Санкт-Петербург",
     "description": "AF Brew — одни из пионеров российского крафта. Петербургская пивоварня основана в 2012 г. тремя энтузиастами – выходцами из различных областей пивоваренной индустрии. Оказавшись в самом авангарде крафтовой революции в России, пивоварня постоянно росла в объемах, первые несколько лет существуя на контрактных мощностях. В 2016 году открыла собственное производство в Санкт-Петербурге в цехах бывшего Степана Разина. Сегодня AF Brew – это миллион литров пива ежегодно, полтора десятка баров, безалкогольное производство и свой собственный фестиваль пива. За время работы пивоварня выпустила сотни уникальных сортов пенного напитка, включая совместные проекты с эстонскими, итальянскими, шведскими и немецкими пивоварнями.",
     "type": "Пивоварня",
     "averageRating": 0,
     "image": "http://109.201.96.70:8081/api/brewery/images/bb5f647bdbe0eda25724b82f02ec05f7.webp"
   },
   {
     "id": 17,
     "name": "STAMM BREWING",
     "city": "Москва",
     "description": "Пивоварня Stamm Beer – небольшое подмосковное семейное предприятие, где варят пиво с 2011 года. Это одна из самых успешных и перспективных пивоварен в России на сегодняшний день. Ассортимент весьма обширен, в линейке можно найти как популярные крафтовые сорта, так и редкие, которые почти невозможно встретить в продаже. Кроме того, пивоварня имеет отдельные мощности для изготовления кислых сортов, длительно выдерживающихся в деревянных бочках из-под вина, а также цех для крепких, мощных сортов. Стоит отметить, что мастера пивоварни одними из первых в России организовали производство бельгийских кислых элей, которые пока все еще очень редки в нашей стране.",
     "type": "Пивоварня",
     "averageRating": 0,
     "image": "http://109.201.96.70:8081/api/brewery/images/be361d5e112bca75babc9ed5efe00992.webp"
   },
   {
     "id": 22,
     "name": "shop",
     "city": "xxxxxxxxx",
     "description": "ccccccccc ccccccc ccccccccccc",
     "type": "Медоварня",
     "averageRating": 0,
     "image": "http://109.201.96.70:8081/api/brewery/images/10_09_2023_17_40_38_news2.png"
   },
   {
     "id": 23,
     "name": "card-image",
     "city": "test",
     "description": "описание",
     "type": "Сидродельня",
     "averageRating": 0,
     "image": "http://109.201.96.70:8081/api/brewery/images/10_09_2023_17_43_36_news3.png"
   },
   {
     "id": 123,
     "name": "Я люблю пиво",
     "city": "Оренбург",
     "description": "описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание описание",
     "type": "Пивоварня",
     "averageRating": 3.5,
     "image": "http://109.201.96.70:8081/api/brewery/images/19_10_2023_10_51_36_left-slide.png"
   },
   {
     "id": 63,
     "name": "demo",
     "city": "Оренбург",
     "description": "description",
     "type": "Медоварня",
     "averageRating": 0,
     "image": "http://109.201.96.70:8081/api/brewery/images/19_09_2023_09_01_26_profile-favorites2.png"
   },
   {
     "id": 92,
     "name": "Hoppy Machine",
     "city": "Ковров",
     "description": "Hoppy Machine Brewery - крафтовая пивоварня, которую в 2019 году в городе Коврове основал Николай, начав производство домашнего пива в гараже. Спрос на качественное пиво рос, и Николай переехал в более просторное помещение, где начал производить и продавать больше пива, в том числе и экспериментальные варианты со специями и фруктами. Hoppy Machine быстро стала популярна, и ее продукцию начали упоминать в местных СМИ. Сегодня это известная пивоварня, которая продолжает экспериментировать со вкусами и производить качественное пиво, продаваемое в магазинах и оптовых компаниях. Hoppy Machine остается верной своим крафтовым корням и стремится создавать уникальные сорта для своих почитателей.",
     "type": "Пивоварня",
     "averageRating": 2.22,
     "image": "http://109.201.96.70:8081/api/brewery/images/23_09_2023_16_40_00_165024898.jpg"
   },
   {
     "id": 93,
     "name": "demo",
     "city": "Москва",
     "description": "описание",
     "type": "Пивоварня",
     "averageRating": 0,
     "image": "http://109.201.96.70:8081/api/brewery/images/23_09_2023_16_42_36_avatar.png"
   },
   {
     "id": 136,
     "name": "Super",
     "city": "Нью-йорк",
     "description": "Супер пивоварня",
     "type": "Пивоварня",
     "averageRating": 5.5,
     "image": null
   },
   {
     "id": 5,
     "name": "Plague Brew",
     "city": "Санкт-Петербург",
     "description": "Проект начался с домашних варок и в основном специализируется на редких и крепких стилях пива и мидов. Plague Brew с 2019 года занимается возрождением старинных рецептов и экспериментирует с малоизвестными направлениями. В линейке пивоварни легко встретить стили, которые будут открытием даже для видавших виды биргиков — к примеру, адамбир или эйсерглин.",
     "type": "Пивоварня",
     "averageRating": 0,
     "image": "http://109.201.96.70:8081/api/brewery/images/07_09_2023_17_11_44_9WcNedqNESc.jpg"
   },
   {
     "id": 364,
     "name": "Справочник Сотрудники",
     "city": "Биробиджан",
     "description": "«Биробиджанская пивоварня»",
     "type": "Сидродельня",
     "averageRating": 0,
     "image": "http://109.201.96.70:8081/api/brewery/images/17_06_2024_10_25_04_avatar.png"
   },
   {
     "id": 4,
     "name": "Selfmade Brewery",
     "city": "Москва",
     "description": "Selfmade Brewery – это пивоварня, созданная с нуля своими руками. Проще говоря, командой, главный постулат которой - это совершенствование своего профессионализма и создание идеального напитка. Наш главный технолог – Александр Громов, профессиональный пивовар, гуру и ас в пивоваренной индустрии. Он имеет в своем портфеле профессиональный диплом инженера-технолога МГУПП по специальности пивоваренное производство. За плечами Александра семинары в Берлинском институте пивоварения, стажировка в Испании на пивоварне Naparbier, опыт работы в Московской Пивоваренной Компании, а также сотни успешных варок на различных пивоварнях России.",
     "type": "Пивоварня",
     "averageRating": 3.15,
     "image": "http://109.201.96.70:8081/api/brewery/images/07_09_2023_17_08_30_f8BSn0wfMJc.jpg"
   }
 ]